spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: netpaper
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    initialize-schema: always
